<?php
// $Id$


/**
 * @file
 * This include file implements views 5.x-1.x functionality on behalf of quiz.module
 */
 
 
/**
 * Implementation of hook_views_api().
 */
function quiz_views_api() {
  return array(
    'api' => '2.0',
  );
} 

function quiz_views_data() {
  return array(
    'quiz_node_results' => array(
      
      // Table Definition
      'table' => array(
        'group' => 'Quiz Results',
        
        // Base tables:
        'base' => array(
          'field' => 'vid',
          'title' => t('Quiz Results'),
          'help' => t('Quiz Results are the results of a quiz a user has taken.'),
          'weight' => 0,
        ),
        'join' => array(
          // This is vid because vid is always more specific.
          'node' => array('left_field' => 'vid', 'field' => 'vid', 'type' => 'INNER'),
        ),
      ),
      
      // Field descriptions:
      'result_id' => array(
        'title' => t('Result ID'),
        'help' => t('The ID of the result.'),
        'field' => array('handler' => 'quiz_views_handler_field_result_id', 'click sortable' => TRUE),
        'argument' => array(
          'handler' => 'view_handler_argument_numeric',
          'name_field' => 'title',
          'numeric' => TRUE,
          'validate_type' => 'result_id',
        ),
        'sort' => 'views_handler_sort',
      ),
      'nid' => array(
        'title' => t('Quiz Node NID.'),
        'help' => t('The ID of the Quiz Node.'),
        'field' => array('handler' => 'views_handler_field', 'click sortable' => TRUE),
        'argument' => array(
          'handler' => 'view_handler_argument_numeric',
          //'name_field' => 'title',
          'numeric' => TRUE,
          'validate_type' => 'nid',
        ),
        'sort' => 'views_handler_sort',
        'relationship' => array(
          'handler' => 'views_handler_relationship',
          'base' => 'node',
          'field' => 'nid',
          'label' => t('node'),
        ),
      ),
      'vid' => array(
        'title' => t('Quiz Node VID.'),
        'help' => t('The Version ID of the Quiz Node.'),
        'field' => array('handler' => 'views_handler_field', 'click sortable' => TRUE),
        'argument' => array(
          'handler' => 'views_handler_argument_numeric',
          //'name_field' => 'title',
          'numeric' => TRUE,
          'validate_type' => 'vid',
        ),
        'relationship' => array(
          'handler' => 'views_handler_relationship',
          'base' => 'node',
          'field' => 'vid',
          'label' => t('node'),
        ),
        'sort' => 'views_handler_sort',
      ),
      'uid' => array(
        'title' => t('User ID.'),
        'help' => t('The ID of the user who took this quiz.'),
        'field' => array('handler' => 'views_handler_field_user', 'click sortable' => TRUE),
        'argument' => array(
          'handler' => 'views_handler_argument_user',
          //'name_field' => 'title',
          'numeric' => TRUE,
          'validate_type' => 'nid',
        ),
        'sort' => 'views_handler_sort',
        'relationship' => array(
          'handler' => 'views_handler_relationship',
          'base' => 'users',
          'field' => 'uid',
          'label' => t('user'),
        ),
      ),
      'time_start' => array(
        'title' => t('Quiz Start Time.'),
        'help' => t('Time the quiz was started.'),
        'field' => array('handler' => 'views_handler_field_date', 'click sortable' => TRUE),
        'argument' => array(
          'handler' => 'views_handler_argument_date',
          //'name_field' => 'title',
          'numeric' => TRUE,
          'validate_type' => 'nid',
        ),
        'sort' => 'views_handler_sort',
      ),
      'time_end' => array(
        'title' => t('Quiz End Time'),
        'help' => t('Time the quiz was finished.'),
        'field' => array('handler' => 'views_handler_field_date', 'click sortable' => TRUE),
        'argument' => array(
          'handler' => 'views_handler_argument_date',
          //'name_field' => 'title',
          'numeric' => TRUE,
          'validate_type' => 'nid',
        ),
        'sort' => 'views_handler_sort',
      ),
      'released' => array(
        'title' => t('Released'),
        'help' => t('The quiz release status'),
      ),
      'score' => array(
        'title' => t('Score'),
        'help' => t('Score on the Quiz.'),
        'field' => array('handler' => 'views_handler_field', 'click sortable' => TRUE),
        'argument' => array(
          'handler' => 'views_handler_argument_numeric',
          //'name_field' => 'title',
          'numeric' => TRUE,
          'validate_type' => 'nid',
        ),
        'sort' => 'views_handler_sort',
      ),
    ),
    //'quiz_node_properties' => array(),
  );
}