<?php

// $Id$

/**
 * @file
 * module file for ajax_quiz quiz module
 */

/**
 * Implementation of hook_help().
 */

function ajax_quiz_help($path, $arg) {
  if ($path == 'admin/help#ajax_quiz') {
    return '<p>' . t('AJAX version of quiz. Successive quiz questions will be loaded in the same page without page reload.') . '</p>';
  }
}

/**
 * Implementation of hook_perm()
 * Valid permissions for this module
 * @return array An array of valid permissions.
 */

function ajax_quiz_perm() {
  return array('access ajax quiz');
}

/**
 * Implementation of hook_menu
 *
 */
function ajax_quiz_menu() {
  $items = array();
  $items['node/%quiz_type_access/ajax-quiz'] = array(
    'title' => t('Take Quiz'),
    'file' => 'ajax_quiz.admin.inc',
    'page callback' => 'ajax_quiz_instruction',
    'page arguments' => array(1),
    'access arguments' => array('access ajax quiz'),
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 *
 * Implementation of hook_init
 * includes the necessary js file(s).
 */
function ajax_quiz_init() {
  //drupal_add_js(drupal_get_path('module', 'ajax_quiz') . '/ajax_quiz.js');
}


/**
 * Implementation of hook_theme().
 */
function ajax_quiz_theme() {
  return array(
    'ajax_quiz_instruction' => array(
      'arguments' => array('instruction' => NULL, 'start' => NULL),
      'file' => 'ajax_quiz.admin.inc',
    ),
  );
}
