<?php
// $Id$

/**
 * The main file for scale.
 *
 * @file
 * Scale question type for the Quiz module.
 *
 * Allows the creation of scale questions (ex: likert scale)
 */

/**
 * Implementation of hook_help().
 */
function scale_help($path, $args) {
  if ($path == 'admin/help#scale') {
    return t('This module provides a scale question type for Quiz.');
  }
}

/**
 * Implementation of hook_menu().
 */
function scale_menu() {  
  return $items;
}

/**
 * Implementation of hook_quiz_question_info().
 */
function scale_quiz_question_info() { 
  return array(
    'scale' => array(
      'name' => 'Scale question',
      'description' => 'Quiz questions that allow a user to choose from a scale.',
      'question provider' => 'ScaleQuestion',
      'response provider' => 'ScaleResponse',
      'module' => 'quiz_question', // All wrapper functions are in that module.
    ),
  );
}
/**
 * Implementation of hook_autoload_info().
 */
function scale_autoload_info() {
  return array(
    'ScaleQuestion' => array('file' => 'scale.classes.inc'),
    'ScaleResponse' => array('file' => 'scale.classes.inc'),
  );
}

/**
 * Implementation of hood_get_answer()
 */
function scale_get_answer($question_nid, $question_vid, $result_id) {
  $sql = "SELECT answer_id, question_vid, question_nid, result_id 
    FROM {quiz_scale_user_answers} 
    WHERE result_id = %d AND question_nid = %d AND question_vid = %d";
  $results = db_query($sql, $result_id);
  
  if (!$results) {
    return FALSE;
  }
  
  return db_fetch_array($results);
}
/**
 * Implementation of hook user.
 */
function scale_user($op, &$edit, &$account, $category = NULL) {
  switch ($op) {
    case 'delete':
      $sql = 'SELECT id FROM {quiz_scale_answer_collection}
              WHERE uid = %d AND id NOT IN
              (SELECT answer_collection_id FROM {quiz_scale_node_properties})';
      $res = db_query($sql, $account->uid);
      while ($res_o = db_fetch_object($res)) {
        $sql = 'DELETE FROM {quiz_scale_answer}
        		WHERE answer_collection_id = %d';
        db_query($sql, $res_o->id);
        $sql = 'DELETE FROM {quiz_scale_answer_collection}
        		WHERE id = %d';
        db_query($sql, $res_o->id);
      }
      break;
  }
}