<?php
// $Id$

/**
 * @file
 * TrueFalse question type for quiz module
 *
 * Allows the creation of true or false questions, which associate one term
 * with another
 */


/**
 * Implementation of hook_help().
 */
function truefalse_help($path, $args) {
  switch ($path) {
    case 'admin/modules#description':
      return t('TrueFalse question type for quiz module.');
    case 'node/add#truefalse':
    case 'admin/help#truefalse':
      return t('A question type for the quiz module: allows you to create truefalse type questions, which connect terms with one another.');
    default:
      break;
  }
}

/**
 * Implementation of hook_quiz_question_info().
 */
function truefalse_quiz_question_info() {
  return array(
    'truefalse' => array(
      'name' => t('True/false question'),
      'description' => t('Quiz questions that allow a user to select true or false (yes/no).'),
      'question provider' => 'TrueFalseQuestion',
      'response provider' => 'TrueFalseResponse',
      'module' => 'quiz_question', // All wrapper functions are in that module.
    ),
  );
}

function truefalse_config() {
  return FALSE;
}

/**
 * Implementation of hook_autoload_info().
 */
function truefalse_autoload_info() {
  return array(
    'TrueFalseQuestion' => array('file' => 'truefalse.classes.inc'),
    'TrueFalseResponse' => array('file' => 'truefalse.classes.inc'),
  );
}