<?php
// $Id$

/**
 * @file
 * Quiz stats
 *
 * Module creates a report to analyse and compare the results of quiz attendees.
 */

/*
 * @function
 * Implementation of hook_init().
 * includes the CSS file
 */
function quiz_stats_init() {
  drupal_add_css(drupal_get_path('module', 'quiz_stats') .'/quiz_stats.css', 'theme');
}

/**
 * @function
 * Implementation of hook_help().
 */

function quiz_stats_help($path, $arg) {
  if ($path == 'admin/help#quiz_stats') {
    return '<p>' . t('Module creates a report to analyse and compare the results of quiz attendees. The reports will be displayed visually using goolge chart API.') . '</p>';
  }
}

/**
 * @function
 * Implementation of hook_perm()
 * Valid permissions for this module
 *
 * @return
 * array of valid permissions.
 */
function quiz_stats_perm() {
  $permission = array('access user stats', 'access author stats');
  // access user dashborad - will allow access to invidual users stats.
  // access author stats - will allow access to all users stats.
  return $permission;

}

/**
 * @function
 * Implementation of hook_menu()
 */
function quiz_stats_menu() {
  global $user;
  $items = array();
  $items['admin/quiz/reports/stats/creator'] = array(
    'title' => t('Quiz Statistics'),
    'description' => t('Generates a report on quiz results for quiz creators.'),
    'file' => 'quiz_stats.admin.inc',
    'page callback' => 'quiz_stats_get_basic_stats',
    'access arguments' => array('access author stats'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/quiz/reports/stats/creator/%/revisions'] = array(
    'title' => t('Quiz Statistics'),
    'description' => t('Generates a report on quiz results for quiz creators.'),
    'file' => 'quiz_stats.admin.inc',
    'page callback' => 'quiz_stats_revision_selector_page',
    'page arguments' => array(5),
    'access arguments' => array('access user stats'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/quiz/reports/stats/creator/%/view'] = array(
    'title' => t('Quiz Statistics'),
    'description' => t('Generates a report on quiz results for quiz creators.'),
    'file' => 'quiz_stats.admin.inc',
    'page callback' => 'quiz_stats_get_adv_stats',
    'page arguments' => array(5),
    'access arguments' => array('access user stats'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['user/%/stats'] = array(
    'title' => t('Result Statistics'),
    'description' => t('Generates a report on quiz results for quiz creators.'),
    'file' => 'quiz_stats.admin.inc',
    'page callback' => 'quiz_stats_get_basic_stats',
    'page arguments' => array(1),
    'access arguments' => array('access user stats'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['user/%/stats/%/view'] = array(
    'title' => t('Result Statistics'),
    //'description' => t('Generates a report on quiz results for quiz creators.'),
    'file' => 'quiz_stats.admin.inc',
    'page callback' => 'quiz_stats_get_adv_stats',
    'page arguments' => array(3, 1),
    'access arguments' => array('access user stats'),
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}


/**
 * @function
 * Implementation of hook_theme().
 */
function quiz_stats_theme() {
  return array(
    'quiz_stats_get_basic_stats' => array(
      'arguments' => array('results' => NULL),
      'file' => 'quiz_stats.admin.inc',
    ),
    'date_vs_takeup_count' => array(
      'arguments' => array('takeup' => NULL),
      'file' => 'quiz_stats.admin.inc',
    ),
    'get_quiz_status_chart' => array(
      'arguments' => array('quiz' => NULL),
      'file' => 'quiz_stats.admin.inc',
    ),
    'quiz_top_scorers' => array(
      'arguments' => array('scorer' => NULL),
      'file' => 'quiz_stats.admin.inc',
    ),
    'quiz_grade_range' => array(
      'arguments' => array('range' => NULL),
      'file' => 'quiz_stats.admin.inc',
    ),
    'quiz_stats_revision_selector' => array(
      'arguments' => array('content' => NULL),
      'path' => drupal_get_path('module', 'quiz_stats') .'/theme',
      'template' => 'quiz_stats_revision_selector',
    ),
    'quiz_stats_charts' => array(
      'arguments' => array('charts' => NULL),
      'path' => drupal_get_path('module', 'quiz_stats') .'/theme',
      'template' => 'quiz_stats_charts',
    ),
  );
}
