<?php

/**
 * @file
 * Questions Export
 *
 * This module allows you to export Quiz questions to portable formats.
 */

/**
 * Implementation of hook_help().
 */

function questions_export_help($path, $arg) {
  if ($path == 'admin/help#questions_export') {
    return '<p>' . t('This module allows you to export Quiz questions to portable formats.') . '</p>';
  }
}

/**
 * Implementation of hook_perm()
 * Valid permissions for this module
 * @return array An array of valid permissions.
 */

function questions_export_perm() {
  return array('export questions');
}

/**
 * Implementation of hook_menu
 *
 */

function questions_export_menu() {
  $items = array();
  $items['admin/quiz/questions_export'] = array(
    'title' => t('Export Quiz Questions'),
    'description' => t('Export Questions is an addon for the Quiz module to export its questions into portable formats.'),
    'file' => 'questions_export.admin.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('questions_export_form'),
    'access arguments' => array('export_questions'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}
