<?php
// $Id$

/**
 * @file
 * Questions Export
 *
 * This module allows you to export Quiz questions to portable formats.
 */

/**
 * Implementation of hook_help().
 */
function questions_export_help($path, $arg) {
  if ($path == 'admin/help#questions_export') {
    return '<p>' . t('This module allows you to export Quiz questions to portable formats.') . '</p>';
  }
}


/**
 * Implementation of hook_perm()
 * Valid permissions for this module
 * @return array An array of valid permissions.
 */
function questions_export_perm() {
  return array('export questions');
}


/**
 * Implementation of hook_menu
 *
 */
function questions_export_menu() {
  
  $items['admin/quiz/import_export'] = array(
    'title' => 'Import and export of quiz',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('export questions', 'import questions'),
    'access callback' => 'quiz_access_multi_or',
    'type' => MENU_NORMAL_ITEM,
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  $items['admin/quiz/import_export/questions_export'] = array(
    'title' => 'Export Questions',
    'description' => 'Export Questions is an addon for the Quiz module to export its questions into portable formats.',
    'file' => 'questions_export.admin.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('questions_export_form'),
    'access arguments' => array('export questions'),
    'type' => MENU_NORMAL_ITEM,
  );

  // Menu item to download item collection in a portable format
  $items['node/%quiz_type_access_load/download'] = array(
    'title' => 'Download',
    'description' => 'Download this quiz into a portable format.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('questions_export_download_form'),
    'access callback' => 'user_access',
    'access arguments' => array('export questions'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Return a form for selecting the export settings
 */
function questions_export_download_form() {
  module_load_include('inc', 'questions_export', 'questions_export.admin');

  $form['exporter'] = array(
    '#type' => 'select',
    '#title' => t('Export format'),
    '#options' => _questions_exporters(),
    '#description' => t('Select the data format to export into.'),
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Download'),
  );

  return $form;
}


/**
 * Handle submission of download form
 *
 */
function questions_export_download_form_submit(&$form, &$form_state) {
  // FIXME hacky way to get the node
  $quiz = node_load(arg(1));
  $exporter = $form_state['values']['exporter'];
  _questions_export_download($quiz, $exporter);
}
